### ISSUE TITLE
Create an new User Interface for app and linking the functions window to it!

### ISSUE THREAD

**Issue by Khushalsarode** [Soumya-Kushwaha/SoundScape#108]
**Is your feature request related to a problem? Please describe.**
Current application when clicked on menu button on mainlanding.py doesn't open an respective wave form code also the drop down in each function code dont work when called.

**Describe the solution you'd like**
so creating an loop application from main page only such that all the function can be called from there and when closed will loop back to main. Also trying to make some changes into main page to adjust buttons. Will thus remove an call from list menu from each functionality page.

**Additional context**
### Before:
![Screenshot 2024-06-01 171311](https://github.com/Soumya-Kushwaha/SoundScape/assets/105520366/f6c6a01c-1bb0-4aa3-9109-8547f72a9b94)

### After & Working:
![Screenshot 2024-06-01 185241](https://github.com/Soumya-Kushwaha/SoundScape/assets/105520366/62ca66af-39ca-44d6-a02f-14227c235067)

@Soumya-Kushwaha
`Can I get this issue assigned! for worked upon?`

Gssoc24

**Comment by Khushalsarode** [comment]
@Soumya-Kushwaha Need Review.

**Comment by Soumya-Kushwaha** [comment]
> @Soumya-Kushwaha Need Review.
Plz link your PR with the issue. It is difficult to trace otherwise.

**Comment by Soumya-Kushwaha** [comment]
What's the update? @Khushalsarode

**Comment by Khushalsarode** [comment]
> What's the update? @Khushalsarode

hey! yes i have added PR I will tag this issue over there.

**Comment by Khushalsarode** [comment]
Working on it! I will reopen PR!
