### ISSUE TITLE
[Feature]: Added Spectral Gating method of noise reduction

### ISSUE THREAD

**Issue by Soubeer** [Soumya-Kushwaha/SoundScape#109]
**Is your feature request related to a problem? Please describe.**
While working on the previous noise reduction task using PCEN, it showed a significant reduction in noise samples unwanted to the individual segment. But I have come across a new method which might help to visualize the effect more and help in higher reduction levels.

**Describe the solution you'd like**
I can use spectral gating to get a better visualization on the work and get better results.

**Describe alternatives you've considered**
Couldn't come across anymore alternatives at this point.

I would like to take this task under GSSOC'24.

Hope I might it to your sight..

Thank You

**Comment by shashbh18** [comment]
Please assign this issue to me.
