### ISSUE TITLE
[feature]:  Add a Title to the Frequency Plot

### ISSUE THREAD

**Issue by Swapnilden** [Soumya-Kushwaha/SoundScape#119]
**Is your feature request related to a problem? Please describe.**
Currently, the frequency plot generated by the application does not have a title, which makes it less informative. Adding a title to the plot will improve clarity and provide a better user experience.

**Describe the solution you'd like**
The absence of a title on the frequency plot makes it less clear what the plot represents, especially for users who might not be familiar with the application's purpose.

**Describe alternatives you've considered**
Add a title to the frequency plot to clearly describe what the plot represents. This can be a simple and descriptive title such as "Frequency Spectrum".

**Additional context**
This enhancement will make the plot more user-friendly and informative.

**Comment by Swapnilden** [comment]
Kindly assign me this issue under GSSOC'24

**Comment by dinxsh** [comment]
have assigned it to you @Swapnilden, lmk if anything is needed, you can directly dm via discord as well

**Comment by Swapnilden** [comment]
Okay 👍
