### ISSUE TITLE
[feature] Issue Template for 'new visualizer'

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/SoundScape#12]
Create an issue template for the SoundScape project to guide contributors when creating new issues. The template will help maintain consistency in contributions and facilitate the review process by providing a clear structure for contributors to follow.

# Requirements

1. Template Structure: 
The issue template should include sections for:
- The description about the visualizer.
- How shall the visualizer be used?
- Any additional context or information relevant to the issue.
- Checklists for contributors to ensure all necessary tasks are completed.

2. Instructions: Provide clear instructions for contributors on how to complete each section of the template.

3. Quality Assurance: Include a checklist to ensure the contributor has completed necessary checks, such as running tests, reviewing their code, and following project guidelines.

4. References: If applicable, provide references to project documentation such as Contributing.md and other related documents.
5. Additional Notes: The PR template should be clear and concise to ensure that contributors can easily follow it.

# Implementation Steps

1. Research: Research best practices for issue templates and review other successful open-source projects for reference.
2. Draft Template: Create a draft template with the sections mentioned in the requirements.
3. Feedback: Gather feedback from the project maintainers and potential contributors to refine the draft template.
4. Finalization: Finalize the issue template and add it to the project repository.
5. Documentation: Add a section in the Contributing.md file explaining how to use the issue template.
6. Testing: Test the issue template with a dummy issue to ensure it works as expected.

# Expected Outcome

Once implemented, the issue template should streamline the issue creation process, making it easier for contributors to raise their issues and for maintainers to review them. This will help maintain a consistent and organized contribution workflow for the SoundScape project.

**Comment by Yatharth31** [comment]
Hey! I m kick starting my open source journey with GSSOC'24. I m interested to contribute to this project. Please assign me this issue.

**Comment by Soumya-Kushwaha** [comment]
Hey @Yatharth31 

Glad to know you're interested in working on this. I'm assigning you.
Let m know if you face any issues or need help.

Thanks.
Happy Contributing! 🚀

**Comment by Nihal-Somarajupalli** [comment]
Hey @Soumya-Kushwaha 

I would like to work on this issue

**Comment by itsmemauliii** [comment]
Hi there! I hope you're doing well! I came across this issue and it seems like something I'd love to work on as a GSSoC contributor'24. I'm eager to dive in and contribute to the project. Let me know how I can get started, and I'll do my best to help out! Please assign me this issue.

**Comment by hasmithagunda123** [comment]
Hi mam Please assign this task to me
