### ISSUE TITLE
Feature Request: Designing a Website Explaining the Characteristics of Soundscape Repo[feature]

### ISSUE THREAD

**Issue by Harish-2003** [Soumya-Kushwaha/SoundScape#124]
#### **Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't easily find comprehensive information about the features, usage, and characteristics of the Soundscape repository. This makes it difficult for new users to understand what the repo offers and how to use it effectively.

#### **Describe the solution you'd like**
I would like a dedicated website that explains the characteristics of the Soundscape repository. The website should provide an overview of the repository and its key features in a clear and concise manner.

#### **Describe alternatives you've considered**
Alternative solutions could include:
- Improving the README file in the repository with more detailed information and links.
- Creating a series of tutorial videos to explain the repository's features.

#### **Additional context**
Creating a website for the Soundscape repo would help users quickly understand its purpose and how to use it. The website could be hosted on GitHub Pages for easy maintenance and updates.

**Comment by Harish-2003** [comment]
hi @Soumya-Kushwaha i kindly request you to create another branch with name ```gh-pages``` in order to make the website visible at ```soumya-kushwaha.github.io/soundscape/```

**Comment by Soumya-Kushwaha** [comment]
Done @Harish-2003

**Comment by Harish-2003** [comment]
I kindly request you to assign some level labels to the issue as well as the PR that I made for this issue. My previous PR did not add any points to my GSSoC leaderboard, so I kindly request you to please look into it.

Thank you.

**Comment by Soumya-Kushwaha** [comment]
Pls follow the PR template.
Link the issues on your PRs.
Tag me and @dinxsh on the new and older PRs, we'll have a look and assign at the earliest.
Also, feel free to discuss all such doubts over Discord now.
