### ISSUE TITLE
feature addition in Spectrogram.py for saving the screenshot of spectrogram

### ISSUE THREAD

**Issue by HarshitaSingh198** [Soumya-Kushwaha/SoundScape#125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HarshitaSingh198** [comment]
I would like to add this feature under Spectrogram.py file ,incorporate a Save button and also providing the save path option for the users.

Please @Soumya-Kushwaha assign this issue to me under labels GSSOC'24 and level mentioned.

**Comment by dinxsh** [comment]
have assigned, looking forward to this @HarshitaSingh198

**Comment by HarshitaSingh198** [comment]
I will ensure to deliver the solution as per expectations.
