### ISSUE TITLE
Enhancement and NEW feature to Waveform.py

### ISSUE THREAD

**Issue by ruhi47** [Soumya-Kushwaha/SoundScape#147]
Summary of Changes to Waveform.py:

- Add error handling for PyAudio initialization.
- Consolidate GUI update functions.
- Add dynamic resizing of the graph canvas.
- Add features to save and load audio data.

I am GSSOC'24 Contributor, please assign me this issue. Thank you!

**Comment by dinxsh** [comment]
save function already exists but if you want to work on the others feel free to @ruhi47

**Comment by ruhi47** [comment]
Thank you !!

**Comment by tkshsbcue** [comment]
i would like to work on this issue please

**Comment by tkshsbcue** [comment]
@dinxsh @ruhi47 i just wanted to ask one thing before starting what do mean by the 3 points like can explain it bit more so that i can fix them more efficiently 
Thanks

**Comment by dinxsh** [comment]
if you mean level numbers its the difficulty of level an issue has to be solved @tkshsbcue

**Comment by tkshsbcue** [comment]
@dinxsh im saying can elaborate issue more what are these issues are
Add error handling for PyAudio initialization.
Consolidate GUI update functions.
Add dynamic resizing of the graph canvas.
Like I'm unable to locate them

**Comment by tkshsbcue** [comment]
@dinxsh i have made a PR request please look into it
