### ISSUE TITLE
[feature] Adding new visualizer for the phase spectrum

### ISSUE THREAD

**Issue by PDBharadwaj** [Soumya-Kushwaha/SoundScape#154]
**Description**
The phase spectrum visualization is crucial for understanding the temporal relationships between frequency components in audio signals. It helps in tasks such as signal synthesis, filtering, and advanced audio processing.

**Comment by PDBharadwaj** [comment]
@dinxsh @Soumya-Kushwaha 
I am GSSoC'24 contributor. I would like to work on this issue. Kindly assign this issue to me.

**Comment by dinxsh** [comment]
sure, have assigned this issue @PDBharadwaj , looking forward to this issue.
