### ISSUE TITLE
Correcting Text Overflow on Visualizer Buttons in the Mainlanding.py file

### ISSUE THREAD

**Issue by Priyaanshucodez** [Soumya-Kushwaha/SoundScape#157]
## Description:
Would like to correct the text overflow on the main visualizers buttons.
![Screenshot (54)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/1484cc91-c5de-486a-a0ab-5be8cf2cc5b9)
With reference to issue #153

**Comment by Priyaanshucodez** [comment]
@dinxsh i have created the issue ...kindly assign me this

**Comment by dinxsh** [comment]
also improve the ui by increasing the font size having better colors and margins @Priyaanshucodez

**Comment by Priyaanshucodez** [comment]
> also improve the ui by increasing the font size having better colors and margins @Priyaanshucodez

ok..Will try my best

**Comment by dinxsh** [comment]
have assigned, looking forward to a better ui! @Priyaanshucodez

**Comment by Priyaanshucodez** [comment]
@dinxsh 
![Screenshot (55)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/d8c3df69-38d3-446b-8db5-65ab01adce75)
i have overcome the text overflow issue ...If its decent i will progress further

**Comment by dinxsh** [comment]
yes looks good, go ahead and make a pr @Priyaanshucodez

**Comment by Priyaanshucodez** [comment]
Improved few files:
1) **Mainlanding.py**
> Increased font size
> Gave it a Dark-Blueish Background 
> Corrected the text overflow  
![Screenshot (59)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/af4ea08d-373b-469d-9946-09006fa77164)

2)**Waveform.py**
> Increased the Heatmap Box layout.
> Increased the text font size
![Screenshot (56)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/7e9fdba4-b8c2-46ec-bf64-f230b4137dbf)


3)Updated the Amplifier-frequency .py and Energy-frequency .py file
![Screenshot (57)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/8a5b6106-2ec0-4e96-8184-793ad0d025d2)
![Screenshot (58)](https://github.com/Soumya-Kushwaha/SoundScape/assets/141406744/a7d8e1c4-2274-4835-bc50-f1a6a35dd050)
....If its good to go i will make a pr .
