### ISSUE TITLE
[feature] Advance the UI features to prioritize beauty and usability 

### ISSUE THREAD

**Issue by saiyam-sandhir** [Soumya-Kushwaha/SoundScape#16]
Hello there! 👋 I've been really impressed by the idea of the project. I'm particularly keen on enhancing the UI to ensure it's not just visually appealing but also user-friendly for both end-users and fellow contributors.

I propose to work on refining UI elements, providing intuitive widgets aligned with the project's theme, and adding more aesthetically pleasing features for graph plotting. My experience in similar projects equips me well for this task.

Also the PySimpleGUI used for the project is proprietary and ask for payment after free trial. So to avoid this i suggest to use CustomTkinter for the same purpose, and i can help you with that 

I'd be thrilled to take on this issue and contribute to making our project even better. Looking forward to your feedback and the opportunity to collaborate on this! 😊 

Here are some images of the UI of the projects i worked on: (You can see them in my profile)

![220828600-61ea8bc3-24e4-4f0a-bab7-4733641ac338](https://github.com/Soumya-Kushwaha/SoundScape/assets/86138251/8f02c6b7-b6f6-40a2-a895-76a7a7613f19)

![220828614-be527c28-d02d-4572-afea-0b77d6a832ad](https://github.com/Soumya-Kushwaha/SoundScape/assets/86138251/8b7d6c7f-9964-4457-9a50-58c264c507a2)

![220828618-92c91998-4c8d-488f-80f9-5841e2e965c3](https://github.com/Soumya-Kushwaha/SoundScape/assets/86138251/585f776b-394d-4d19-9582-e22aa8ee7c67)

![251272373-6de37662-4edf-492f-810b-1914fa8f0808](https://github.com/Soumya-Kushwaha/SoundScape/assets/86138251/bd6caa77-a2a4-4cca-a74b-261454703950)

![251272423-96265269-660a-434b-8580-7e362d8d2630](https://github.com/Soumya-Kushwaha/SoundScape/assets/86138251/8030a6a7-2b15-4076-8174-b89cb097c4f2)

**Comment by Soumya-Kushwaha** [comment]
@saiyam-sandhir Please tell me more about how do you plan to update the UI.
And I'll be happy to assign you the issue.

**Comment by saiyam-sandhir** [comment]
Yeh sure,

### Which library i am going to use:

- I plan to use a library called [CustomTkinter](https://github.com/TomSchimansky/CustomTkinter), maintainer: [TomSchimansky](https://github.com/TomSchimansky).
- He has made a [project](https://github.com/TomSchimansky/GuitarTuner) with PyAudio so you don't have to worry about the compatibility. 
- CustomTkinter is build on top of Python's Tkinter and at its very stable state.

## My plans:

### Current Stage Plans:

- To turnaround your entire need to use PySimpleGUI to more beginner friendly, flexible and expandable library, i.e., CustomTkinter.
- make the current GUI and theme more suitable to your needs and fun, like if want to have pop up animations on buttons like in a react or mobile application.
- Give more colors to graphs (as per use choice).

### Future Plans:

- Provide more theme related widgets like scrollers, buttons, etc that you can easily incorporate in your program so you don't have to worry about incorporating and designing new widget everytime and putting them in an order.
- farther customizations as per your need or orther contributors need.

## What i need

- First of all, some time, as i really loved the project and would really love to contribute on it even after the event ends. But current i am a college student, and my term ends are in there way, so i work with my heightest efficiency after 28th of may (but still contribute along the way).
- further smaller issues to be set up so the i can keep up with what to do.

## So this is all i have planned with the project, and i hope you liked it. I wish you don't mind my demands its totally your choice. I hope we can work together

**Comment by Soumya-Kushwaha** [comment]
@saiyam-sandhir This sounds great.
I'd suggest you to create separate issues (max 1 issue can be assigned at a time) and continue fixing those.
And when you're done with your exams, you can increase the pace.

**Comment by saiyam-sandhir** [comment]
Ok @Soumya-Kushwaha, thanks a lot for this opportunity, i will give my best.

currently you have assigned me with issue #7 improvise documentation, once done with that i will continue with the UI features
