### ISSUE TITLE
[feature]:  Add a new Lissajous Curves Visualizer

### ISSUE THREAD

**Issue by abckhush** [Soumya-Kushwaha/SoundScape#166]
**Describe the solution you'd like**
Lissajous curves are parametric equations that describe complex oscillating patterns. They are particularly interesting for visualizing sound as they can react dynamically to the audio signal.

@dinxsh @Soumya-Kushwaha Kindly assign me.

**Comment by Cheshta17** [comment]
Hey, I would love to contribute to this issue.
