### ISSUE TITLE
Add Code of Conduct for Contribution

### ISSUE THREAD

**Issue by Saksh8** [Soumya-Kushwaha/SoundScape#17]
I wish to add the  code of conduct which needs to be followed for contributing in this project

**Comment by Santhosh-Siddhardha** [comment]
Hi @Soumya-Kushwaha 
I would like to work on this issue, could please assign me this issue

**Comment by ldneal** [comment]
Hi Mam Pls Assign Me

**Comment by hasmithagunda123** [comment]
hello please assign this task to me

**Comment by bhanushri12** [comment]
Hello @Soumya-Kushwaha 
I would like to work on this issue, waiting to make improvements.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by Soumya-Kushwaha** [comment]
@Saksh8 please go ahead. Let me know if you need any help.

Happy Contributing! 🚀

**Comment by KartikRajOfficial** [comment]
Hey @Saksh8 I would like to add Code Of Conduct for this repository

**Comment by SuhaniStark** [comment]
I wish to add the code of conduct which needs to be followed for contributing in this project... please assign me the project

**Comment by Soumya-Kushwaha** [comment]
@Saksh8 Well done on this one.
Please feel free to take up more issues.
