### ISSUE TITLE
[new_visualizer]: Add a new Chroma Feature Visualizer

### ISSUE THREAD

**Issue by abckhush** [Soumya-Kushwaha/SoundScape#172]
## Description:
The Chroma Feature Visualizer is an enhancement to the SoundScape project that provides a visual representation of chroma features, which capture the 12 different pitch classes (C, C#, D, etc.) in a musical audio signal. 

## How to Use:
The Chroma Feature Visualizer is designed to be integrated into the SoundScape project as an additional visualization option. Users can select this visualizer to see the chroma features of the audio input in real-time.

## Implementation Details:

- **Algorithm/Methodology**: The audio is processed in real-time and the chroma features are computed using Short-Time Fourier Transform (STFT). The chroma features are then converted to a decibel scale for better visual representation.
- **Dependencies**: librosa, matplotlib, numpy

**Additional Context:**
Include any relevant information such as specific use cases or technical details.

## Checklists
**Checklist for Contributors**
- [X] I have read and followed the contribution guidelines in `Contributing.md`.
- [X] I have reviewed existing issues and pull requests to ensure this visualizer has not already been proposed or implemented.
- [X] I have provided a clear and detailed description of the new visualizer.
- [X] I have ensured the proposed enhancement aligns with project goals and guidelines.
- [X] I have tested the visualizer in different environments or scenarios.

**Quality Assurance Checklist**
- [X] Run tests to validate the changes.
- [X] Review code for readability, maintainability, and adherence to coding standards.
- [X] Confirm backward compatibility with existing features.
- [X] Address any potential performance impacts.

## Instructions for Contributors
1. Provide a clear and concise description of the proposed enhancement.
2. Include steps to reproduce the issue if reporting a bug.
3. Attach relevant screenshots or code snippets to support your proposal.
4. Follow the provided checklists to ensure all necessary tasks are completed.
5. Assign appropriate labels and assignees based on the nature of the issue.

## References
- [Contribution.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Contribution.md)
- [Installation.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/Installation.md)
- [References.md](https://github.com/Soumya-Kushwaha/SoundScape/blob/main/References.md)

**Additional Notes:**
- Make sure to stick to the issue template to facilitate the review process.
- Feel free to engage with maintainers or other contributors for feedback or assistance.

Thank you for your contribution! Please submit your issue and wait for further review and feedback from the project maintainers.

**Comment by dinxsh** [comment]
assigned @abckhush
