### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [Soumya-Kushwaha/SoundScape#23]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by Priyanshu2631** [comment]
I m a contributor of GSSOC'24, please assign this issue to me

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by iamrudhresh** [comment]
Please assign this issue to me under gssoc 24.

**Comment by ldneal** [comment]
I'm contributor pls assign me this issue in gssoc'24

**Comment by akshatsharma2407** [comment]
Hello, I want to contribute in your project, please assign it to me.

**Comment by nidhivk01** [comment]
hello, Can I contribute to the project. Could you please assign me this .
