### ISSUE TITLE
Further Ideas To Add:

### ISSUE THREAD

**Issue by KushalTrivedi19032005** [Soumya-Kushwaha/SoundScape#25]
1) Another way to create sound waves could be to add an audio file and generate plot, besides uploading and recording from a microphone in the moment.
2) Display the note corresponding to the audio signal, for example, A# or C, this could be an important feature for musicians.
3) Audio-based color generation: Depending on the audio signal, have a color corresponding to the signal amplitude in the background. This would improve visual appearance.

Can you assign me to these 3 issues? @Soumya-Kushwaha

**Comment by Soumya-Kushwaha** [comment]
@KushalTrivedi19032005 Sounds really great.
Let's keep that as an alternative and not a replacement. Both the techniques have their own importance.

Please create separate issues and I'll happily assign you - but, one at a time (as per the rules).

**Comment by KushalTrivedi19032005** [comment]
Surely, I will create them as separate issues.

**Comment by Soumya-Kushwaha** [comment]
Not as of now.
We'll probably be having separate channels in the GSSOC server itself soon. Let's wait for a couple of days. Else I'll create one.
