### ISSUE TITLE
requirments.txt includes modules that are not being used in any of the script under this project

### ISSUE THREAD

**Issue by lorforlinux** [Soumya-Kushwaha/SoundScape#3]
@Soumya-Kushwaha Can you please confirm if all the modules listed in requirements.txt are required for this project? I had to install a lot of large AI/ML & Intel acceleration modules which might not be required for the project. Please also confirm if you created this file from the project itself or if you used a requirement.txt from one of your other projects.

If all these libraries are actually required for the project then please provide a dependency graph and a disclaimer for users.

**Comment by Soumya-Kushwaha** [comment]
The earlier file wasn't entirely wrong. But I updated the file for only necessary dependencies.
