### ISSUE TITLE
[feature] Feature Implementation: Pause/Resume Audio Stream, Save Functionality, and GUI Updates

### ISSUE THREAD

**Issue by RavindranathTagor** [Soumya-Kushwaha/SoundScape#36]
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem. It is an enhancement to the existing functionality of the Amplitude-Frequency-Visualizer.py script in the **"Amplitude-Frequency-Visualizer"** project.

**Describe the solution you'd like**
I have implemented several new features that I believe would enhance the functionality and user experience of the project:

1. Added the ability to pause and resume the audio stream through pause and resume functions. These are tied to `"Pause" `and `"Resume"` buttons in the GUI.

2. Implemented a save function that allows users to save the audio data to a `.wav file` and the frequency plot to a `.png file`. This is tied to a `"Save"` button in the GUI.

3. Introduced an audio buffer `(_VARS["audioBuffer"])` to store all the audio data for saving purposes.

4. Enhanced the frequency plot with gridlines and a legend.

5. Imported the `soundfile library` to facilitate saving of audio data to a` .wav file`.

6. Adjusted the canvas size of the graph from` (500, 500)` to `(600, 600) `for better visibility.

7. Updated the GUI layout to accommodate the new `"Pause", "Resume", and "Save"` buttons.

**Describe alternatives you've considered**
N/A. These features are additions to the existing functionality and do not replace any current features.

**Additional context**
I would like to contribute these changes to the main project. Could you please **assign me** to an issue where I can submit these updates as a pull request? Given the complexity of these changes, I would like to request that this issue be labeled as part of **GSSoC'24** and marked as **Level 3**.

Thank you for considering my contributions. I look forward to your feedback.

**Comment by Soumya-Kushwaha** [comment]
@RavindranathTagor Please go ahead.
