### ISSUE TITLE
[bug] Error in ProgressBar Update

### ISSUE THREAD

**Issue by Raghuveer22** [Soumya-Kushwaha/SoundScape#37]
**Describe the bug**
Upon attempting to close the application after initiating a recording session and subsequently closing the window, an error occurs related to progress bar update, preventing the application from terminating gracefully. The error persists regardless of how many times the application is closed via the window close button.
**To Reproduce**
1. run `python waveform.py` or `python amplitude-frequency-visualizer.py` or `python spectogram.py`
2. Click on listen and speak 
3. Now close the application thorugh window 
4. Now this shows error in progressbar update no matter how many times you close from there it wont terminate gracefully. 

**Expected behavior**
It should close the application gracefully but it's not doing that it asks to terminate the application.

**Screenshots**
![image](https://github.com/Soumya-Kushwaha/SoundScape/assets/94948420/eceb0e66-a0a7-4d10-8cbb-a3570eac32df)

**Additional context**
I would like to contribute these changes to the main project. Could you please assign me .I would like to request that this issue be labeled as part of GSSoC'24 and marked as Level 2.

**Comment by Soumya-Kushwaha** [comment]
@Raghuveer22 Please go ahead.

**Comment by tejaswini4996** [comment]
shall I work on this isssue

**Comment by tejaswini4996** [comment]
Shall work on this issue
