### ISSUE TITLE
Add a demo video in the README for better understanding. of the project.

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/SoundScape#40]

**Comment by Harish-2003** [comment]
can you assign this to me i can work upon this...! i think of recording my screen saying how to fork and clone soundscape repo and running everyfiles explaning each file and how it works? or do i need to do anything else? please let me know

**Comment by Soumya-Kushwaha** [comment]
Yes, please explain about forking, cloning, contributing guidelines, code of conduct.
Basically everything a new person needs to understand as a prerequisite. 
You can show the functioning of 1-2 processors/visualizers that are currently added.

Assigning you, please go ahead.

**Comment by tejaswini4996** [comment]
Will you assign it to me
