### ISSUE TITLE
[feature] Enhancements for User Interface Readability and Guidance

### ISSUE THREAD

**Issue by RavindranathTagor** [Soumya-Kushwaha/SoundScape#52]
**Is your feature request related to a problem? Please describe.**
The current method of accessing GUI elements, such as the "graph" element from the "window" dictionary stored in the "_VARS" dictionary, is not very intuitive or readable.

**Describe the solution you'd like**
I propose the following changes to improve the readability and user experience of the application:

1. Change the `AppFont` variable from "Any 16" to "Helvetica" for better readability.
2. Add tooltips to the `sg.Graph` and all `sg.Button` elements in the layout to provide better user guidance.
3. Add a `sg.Text` element before the progress bar to label it as "Progress:" to make it clear what this bar represents.
   **Screenshots:** 
   Before
   ![Screenshot 2024-05-12 224559](https://github.com/Soumya-Kushwaha/SoundScape/assets/133690792/e7862874-c598-49f6-a5f0-b4c9e79f5015)
   After
![Screenshot 2024-05-12 224946](https://github.com/Soumya-Kushwaha/SoundScape/assets/133690792/5b36a9cb-5514-4ef6-8396-a8b68e8a4f20)

**Describe alternatives you've considered**
Not applicable. The changes suggested do not have direct alternatives as they are specific improvements to the user interface. They are based on standard UI/UX principles and are generally applicable across different GUI libraries or frameworks.

**Comment by RavindranathTagor** [comment]
Please add level label!

**Comment by Soumya-Kushwaha** [comment]
I will add that based on the work done.
