### ISSUE TITLE
[Feature]:Adding methods to reduce sound noise

### ISSUE THREAD

**Issue by Soubeer** [Soumya-Kushwaha/SoundScape#56]
We go through a variety of sound levels and zones in our daily life, even when we are sleeping. This may not look like a big deal to us but it can surely create problems with ongoing age and development of our surroundings. This problem can be reduced tho,not by letting others help you with their actions but analyzing the noise levels and acting accordingly.

The solution can initially deal with the noise level analyzation ,which can source out the frequencies(highs and lows) and filter them out. Using time frequency channels next ,we can have non linear compression which can compress out sections where it needs the most accurately which is super useful for acoustic events. We can have different visualizations via different spectrums to see the frequency distribution which we are dealing with.

There are some methods which I can think of but not sure if all would be possible to work with. As for now ,I can implement the primary method which is straight forward and not very tacky for users who might not have extensive knowledge in this field.

**Additional context**
I would definitely like to try out the other methods for this issue, so should I create a new issue if I am able to successfully do it after this task is done?

**Comment by tejaswini4996** [comment]
Shall I work on this issue?

**Comment by Soubeer** [comment]
@Soumya-Kushwaha can i be assigned a level ? I have already submitted the work 2 weeks ago in the PR.
Kindly check it please. It includes the total waveform to see how the noise detection and reduction works
