### ISSUE TITLE
Minor Corrections and Improvements for SoundScape Description

### ISSUE THREAD

**Issue by kvdevlopment** [Soumya-Kushwaha/SoundScape#60]
**Description:**
The current description of SoundScape provides a comprehensive overview of the project, detailing its functionality, visualizers, usage, contribution guidelines, and references. However, there are a couple of minor corrections and improvements that could enhance its clarity and consistency.

**Spectogram Spelling:**  The term "Spectogram" should be corrected to "Spectrogram" for accuracy.

**Visualizer Title Clarification:** The title "Frequency v/s Amplitude" could be clarified for better understanding and consistency. It can be rephrased as "Frequency vs. Amplitude" or "Frequency versus Amplitude."

**You can refer  the mistake here **
![2024-05-14 03_18_40-](https://github.com/Soumya-Kushwaha/SoundScape/assets/109462746/48bc6afb-003a-4764-a478-f59e9084225a)
![2024-05-14 03_19_32-Window](https://github.com/Soumya-Kushwaha/SoundScape/assets/109462746/d05995c7-a110-414e-b3f0-616be4007e6a)

**Comment by kvdevlopment** [comment]
Hello @Soumya-Kushwaha 
Can you please assign me this issue.

**Comment by Jhalak-Gupta** [comment]
I am interested in this task. Pls assign it to me under GSSOC'24 so that I can contribute to this project. I am good enough at my skills to complete this task efficiently.

**Comment by RohanJobanputra** [comment]
Hello! i would like to work on this, please assign me.

**Comment by RohanJobanputra** [comment]
Hello! i can still notice the unchanged errors in README file, spectogram and v/s precisely. I would request you to assign me the task. Thank You!

**Comment by why-Radhika** [comment]
I have made the necessary changes and have created a pull request. Could you please assign this issue to me so that the PR can be merged?

**Comment by JyotikaJayani-08** [comment]
#103 Please review the changes and approve.
