### ISSUE TITLE
Add Menu Bar for Running Spectrogram and Waveform Visualizers

### ISSUE THREAD

**Issue by ashimasaini2001** [Soumya-Kushwaha/SoundScape#61]
I propose adding a menu bar to the top of the application window to enhance the usability and accessibility of the project. This menu bar will include options to run the spectrogram, Frequency v/s Amplitude and waveform visualizers with a simple click.

Currently, users must manually start the visualizations, which can be cumbersome and not intuitive, especially for those unfamiliar with the underlying code.

I want this issue to be assigned to me

**Comment by Sailza** [comment]
As a contributor to GSSOC 2024, I'm eager to take on tasks. Could you please assign me this task for completion?

**Comment by manyahegde** [comment]
I would like to contribute. Please assign me the task.

**Comment by ashimasaini2001** [comment]
@Soumya-Kushwaha Could you please assign me this task?
