### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Vaibhavv1703** [Soumya-Kushwaha/SoundScape#67]
A GUI which can be used to open the graphs.
I want this issue to be assigned to me.

**Comment by Vaibhavv1703** [comment]
Assign this issue to me

**Comment by Sailza** [comment]
As a contributor to GSSOC 2024, I'm eager to take on tasks. Could you please assign me this task for completion?

**Comment by Soumya-Kushwaha** [comment]
Please share more about the GUI @Vaibhavv1703

**Comment by Vaibhavv1703** [comment]
> Please share more about the GUI @Vaibhavv1703

Instead of opening the other files for graph, I created a single program which can be used open all other graphs
![Screenshot 2024-05-20 124143](https://github.com/Soumya-Kushwaha/SoundScape/assets/147066136/f4b8b069-ddad-46c6-a19f-11238ed1313d)
This is how it looks

**Comment by dinxsh** [comment]
looks great, looking forward to this. have assigned this to you! lmk if you need anything directly via discord @Vaibhavv1703
