### ISSUE TITLE
Add draw_heat_map function to visualize the graph with labels

### ISSUE THREAD

**Issue by anirudh-hegde** [Soumya-Kushwaha/SoundScape#74]
Add the above mentioned function to Intensity-vs-Frequency-and-time.py file

**Comment by kumargautam02** [comment]
Hi anirudh, i am interested in working on this issue, kindly assign it to me.

**Comment by anirudh-hegde** [comment]
> Hi @anirudh-hegde anirudh, i am interested in working on this issue, kindly assign it to me.

Hey @kumargautam02 maintainer of the project will assign you. However I'm a contributor.

**Comment by anirudh-hegde** [comment]
Hi @Soumya-Kushwaha can I please get a response
