### ISSUE TITLE
[feature]: Containerize this application

### ISSUE THREAD

**Issue by rohansen856** [Soumya-Kushwaha/SoundScape#77]
### Describe the feature

This app uses a specific version of python. So, it may not work on everybody's device. Containerizing the application using docker would make it easier and more developer friendly.
Please assign me this issue under GSSOC'24

### Add ScreenShots

![image](https://github.com/Clueless-Community/scrape-up/assets/108976786/16139e17-7c7d-479c-88dd-c8eb45a2582a)

**Comment by Soumya-Kushwaha** [comment]
Duplicate issue #32

**Comment by rohansen856** [comment]
@Soumya-Kushwaha i have solved this issue in pr #138. thank you.
