### ISSUE TITLE
Create PR Templates

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/SoundScape#8]
Create PR templates for the SoundScape project to guide contributors when submitting pull requests. PR templates will help maintain consistency in contributions and facilitate the review process by providing a clear structure for contributors to follow.

# Requirements

1. Template Structure: 
- The PR template should include sections for:
- PR title and description.
- Changes and additions made in the pull request.
- Testing and validation done for the changes.
- Any additional context or information relevant to the PR.
- Checklists for contributors to ensure all necessary tasks are completed.

2. Instructions: Provide clear instructions for contributors on how to complete each section of the template.

3. Quality Assurance: Include a checklist to ensure the contributor has completed necessary checks, such as running tests, reviewing their code, and following project guidelines.

4. References: If applicable, provide references to project documentation such as Contributing.md and other related documents.
5. Additional Notes: The PR template should be clear and concise to ensure that contributors can easily follow it.

# Implementation Steps

1. Research: Research best practices for PR templates and review other successful open-source projects for reference.
2. Draft Template: Create a draft template with the sections mentioned in the requirements.
3. Feedback: Gather feedback from the project maintainers and potential contributors to refine the draft template.
4. Finalization: Finalize the PR template and add it to the project repository.
5. Documentation: Add a section in the Contributing.md file explaining how to use the PR template.
6. Testing: Test the PR template with a dummy pull request to ensure it works as expected.

# Expected Outcome

Once implemented, the PR template should streamline the pull request process, making it easier for contributors to submit their changes and for maintainers to review them. This will help maintain a consistent and organized contribution workflow for the SoundScape project.

**Comment by Soumya-Kushwaha** [comment]
Hey @RavindranathTagor 

Glad to know you're interested in working on this. I'm assigning you.
Let m know if you face any issues or need help.

Thanks.
Happy Contributing! 🚀

**Comment by Kochurii** [comment]
I would like to work on this issue. Can you please assign this to me?
