### ISSUE TITLE
[feature] Add Frequency vs Energy Visualization in SoundScape

### ISSUE THREAD

**Issue by Saksh8** [Soumya-Kushwaha/SoundScape#81]
I would like to add Python code that could plot Frequency vs Energy for a particular sound.

**Comment by SanskariWolf** [comment]
I'm participating in GSSoC'24 and found this issue in your repo I'd like to work on. Could you please assign it to me?

**Comment by kaviya2478** [comment]
Can you assign this task to me.

**Comment by Soumya-Kushwaha** [comment]
@Saksh8 any update?
