### ISSUE TITLE
[feature]Create and Deploy Streamlit App for Real-time Audio Visualization

### ISSUE THREAD

**Issue by revanth1718** [Soumya-Kushwaha/SoundScape#83]
We need to create a Streamlit application that visualizes real-time audio input through a microphone. The app should provide two types of visualizations: waveform and spectrogram. Once the app is developed, it should be deployed to a free hosting service for easy access and use.

I am participating in GSSOC'24

**Comment by Soumya-Kushwaha** [comment]
I am really looking forward to this @revanth1718 .
Please go ahead with it.
In case of doubts, feel free to discuss with @dinxsh

**Comment by revanth1718** [comment]
ok mam

**Comment by Soumya-Kushwaha** [comment]
@revanth1718 any update?

**Comment by revanth1718** [comment]
mam can you please give me 1 week time?
