### ISSUE TITLE
[feature] Workflow for closing Old PRs 

### ISSUE THREAD

**Issue by Ratangulati** [Soumya-Kushwaha/SoundScape#87]
**Is your feature request related to a problem? Please describe.**
The purpose of this feature is to automate the management of open pull requests (PRs) in a repository. It ensures that outdated or abandoned PRs are closed promptly, which helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

**Comment by dinxsh** [comment]
closing since duplicate and spamming similar issues
