### ISSUE TITLE
[feature]  Auto Commenting feature for PR Raised

### ISSUE THREAD

**Issue by Ratangulati** [Soumya-Kushwaha/SoundScape#91]
**Is your feature request related to a problem? Please describe.**
This feature is designed to solve the issue of delayed and inconsistent communication after pull requests (PRs) are raised. By automatically adding comments to PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This helps to create a positive and supportive environment for collaboration, which in turn encourages ongoing participation and engagement from contributors.n and engagement from contributors.

**Comment by dinxsh** [comment]
closing since duplicate and spamming similar issues
