### ISSUE TITLE
[doc]: Adding few sections to  readme document.

### ISSUE THREAD

**Issue by rithika212k3** [Soumya-Kushwaha/SoundScape#98]
Hi @Soumya-Kushwaha ,
I would like to add thanks to the contributor section and support section to the readme doc. Can you please assign this issue to me?
It makes the document look more beautiful and it shows your love towards the contributors.
screenshot is attached below. In this way, I want to make changes at the end of the readme document.
![tnxs_support](https://github.com/Soumya-Kushwaha/SoundScape/assets/158501895/dc81b57a-ec71-4061-92a6-a5919848c7f3)

**Comment by shashbh18** [comment]
Please assign this issue to me.
