### ISSUE TITLE
Bug Fixes , Feature Enhancements and Code Optimizations .

### ISSUE THREAD

**Issue by Ankush-ai** [Soumya-Kushwaha/SoundScape#99]
**Code File: RealTime_Mic_to_Frequency_Plot.py**

**Bug Fixes:**

1. Resolved potential memory leaks by properly closing the PyAudio stream and terminating the PyAudio instance when the application exits.
2. Handled the case where PyAudio initialization fails due to device errors.
3. Feature Enhancements:
4. Added a tooltip to the frequency graph for better user experience.
5. Implemented a feature to save the generated frequency plot and recorded audio to the user-specified directory.

**Code Optimizations:**

1. Streamlined the code structure for better readability and maintainability.
2. Used PySimpleGUI's popup_get_folder method for selecting the directory to save the files, improving the user interface.
3. Utilized PySimpleGUI's finalize=True parameter for layout finalization, improving performance.
4. Code File: RealTime_Mic_to_Spectrogram_Plot.py

**Bug Fixes:**

1. Properly closed the PyAudio stream and terminated the PyAudio instance to prevent potential memory leaks.
2. Handled the case where PyAudio initialization fails due to device errors.
3. Feature Enhancements:
4. Implemented a real-time spectrogram plot of the audio input.

**Code Optimizations:**

1. Streamlined the code structure for better readability and maintainability.
2. Used PySimpleGUI's finalize=True parameter for layout finalization, improving performance.
3. Code File: RealTime_Mic_to_Waveform_Plot.py

**Bug Fixes:**

1. Properly closed the PyAudio stream and terminated the PyAudio instance to prevent potential memory leaks.
2. Handled the case where PyAudio initialization fails due to device errors.
3. Feature Enhancements:
4. Added a real-time display of the audio waveform.
5. Users can listen to the audio input and visualize the waveform simultaneously.
6. Progress bar indicates the maximum sound level.

**Code Optimizations:**

1. Streamlined the code structure for better readability and maintainability.
2. Used PySimpleGUI's finalize=True parameter for layout finalization, improving performance.
3. These changes aim to improve the functionality, stability, and user experience of the applications while optimizing the code for better performance and maintainability.

**### For the above, I made the changes, please allow me to Raise a PR and I request you to merge IT .**

**Comment by Wahid7852** [comment]
you can create a PR and ask him to review / merge
no point in creating issue asking for PR
